### ISSUE TITLE
Update Readme: Config

### ISSUE THREAD

**Issue by Diegogagan2587** [javiertury/babel-plugin-transform-import-meta#14]
# Suggested changes:
 
 I think would be great if you could specify in the readme where we should add the next:
 
![image](https://github.com/javiertury/babel-plugin-transform-import-meta/assets/61764778/5f53161c-e27f-4073-9be5-3771365bdf66)

I think that would make crystal clear the readme. 
Thanks for reading.

**Comment by javiertury** [comment]
Thanks for the suggestion!
